### ISSUE TITLE
Error in Mini Batch 

### ISSUE THREAD

**Issue by nthakor** [rajarsheem/libsdae#1]
The mini batch function may generate same sample over
There is no removal already used indices

Also issue with mask noise

Following error: 

```
File "algorithms/deepautoencoder/stacked_autoencoder.py", line 42, in add_noise
    frac = float(self.noise.split('-')[1])
```

**Comment by rajarsheem** [comment]
I will look into the masking issue, but currently on some other things. So, can you make a PR if you have already fixed the issue or you want to.

Regarding the mini batch thing, you should rely on [random sampling](https://en.wikipedia.org/wiki/Simple_random_sample). If you remove after each sampling, you are not giving equal weight-age to every datapoint. Whether same sample is generated multiple times(which is quite rare) or highly overlapping sample, that should be probabilistic in nature.

**Comment by OnTheRicky** [comment]
I'm not sure how to make changes, but removing the assert for the mask noise seems to work for me. Surely it's just another small fix to keep the assert, but make it work right

**Comment by rajarsheem** [comment]
I noticed a bug there related to mask noise. I will be pushing soon!

**Comment by rajarsheem** [comment]
Hope the issue is solved now. Kindly check if the latest commit works!
