### ISSUE TITLE
Other dataset than mnist

### ISSUE THREAD

**Issue by PatelAxita** [rajarsheem/libsdae#10]
I have just started learning denoising autoencoders but I want to import dataset of images than mnist what can be done to do so . I have tried giving path name and assigning it to a variable but im getting a type error.

**Comment by rajarsheem** [comment]
Can you please share the exact error accompanied by the code that you have written ?

**Comment by rajarsheem** [comment]
Due to inactivity, I am closing this issue. Feel free to re-open if you want.
