### ISSUE TITLE
UnboundLocalError: local variable 'l' referenced before assignment (at stacked_autoencoder.py#L128)

### ISSUE THREAD

**Issue by alvaroabascar** [rajarsheem/libsdae#11]
Hi @rajarsheem, just got across a failure due to *l* not being defined in [this line](https://github.com/rajarsheem/libsdae-autoencoder-tensorflow/blob/89205796d0950f6974dbcc592f8a9e4a9233e50a/deepautoencoder/stacked_autoencoder.py#L128).

Context:

![screenshot from 2018-04-05 18-51-17](https://user-images.githubusercontent.com/7307772/38379939-92d0518a-3902-11e8-92c0-b16b60a0c9c0.png)

**Comment by rajarsheem** [comment]
Hi, thanks for reporting. That assignment was unnecessary. So removed it.
