### ISSUE TITLE
Content of data/ in top directory

### ISSUE THREAD

**Issue by erlebach** [rajarsheem/libsdae#12]
Hi, 

What do the two files inside data/ represent? I found no description. Thanks.

  Gordon

**Comment by erlebach** [comment]
More serious question: I took the example test.py provided, and replace the "linear" activations by relu activations. Result: I printed x[i] at the end of the fit() function. All x[i] were identical. This was not the case with the linear activation function. Why would this be? Thanks.

Try running test.py with: 

model = StackedAutoEncoder(dims=[200, 200], activations=['relu', 'relu'], epoch=[
                           3000, 3000], loss='rmse', lr=0.007, batch_size=100, print_step=200)

   Gordon

**Comment by rajarsheem** [comment]
Hey, I am sorry for replying so late. Is the issue still there?

**Comment by lenghanyan** [comment]
Hey,how can this program display the extracted feature images?
