### ISSUE TITLE
AutoEncoder Graph Construction

### ISSUE THREAD

**Issue by akbari59** [rajarsheem/libsdae#6]
Hi Rajarshee Mitra,

I have question regarding your code. I am confused how your code construct the connections between layers. Specifically, in line 63 of stacked_autoencoder.py, you called the run function for different layers . it seems for me that you construct n different auto-encoders instead of one stacked with n hidden layers.

Best regards,
Mohammad

**Comment by dawnranger** [comment]
Notice that the variable x is the output of current layer, and then is passed to the next layer as input data. So I think the code is ok.

**Comment by ljvmiranda921** [comment]
I believe the autoencoder here is being trained via [greedy layerwise unsupervised training](https://papers.nips.cc/paper/3048-greedy-layer-wise-training-of-deep-networks.pdf), thus each layer is trained one-by-one.

**Comment by rajarsheem** [comment]
Thanks, @dawnranger  and @ljvmiranda921 !
@akbari59 , that's how a stacked auto-encoder differs from a multi layered NN. I hope your confusion has gone!
