### ISSUE TITLE
Blas GEMM launch failed

### ISSUE THREAD

**Issue by kxxwz** [rajarsheem/libsdae#7]
Hi, Rajarshee Mitra!
Thank you very much for your code! But when I tried running your code on my computer, I always got the error shown below:

'''
InternalError: Blas GEMM launch failed : a.shape=(100, 784), b.shape=(784, 200), m=100, n=200, k=784
	 [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_x_0_0/_7, Variable/read)]]
'''
where 100 is batch_size, 784 and 200 are dimensions.

Can you offer me some help!
Thanks a lot!
Phil

**Comment by kxxwz** [comment]
After I reinstall your package, it works again! I'm a little bit confused.

**Comment by rajarsheem** [comment]
Hi @CoolPhilChen , is it fine right now ?

**Comment by kxxwz** [comment]
Hi @rajarsheem, it works fine now! I think this problem may have something to do with my python kernel, for restarting the kernel solves it. Anyway thanks a lot!
